#!/bin/sh

# Helper function for error reporting.
die() { [ $# -gt 0 ] && echo "ERROR: $*" >&2; exit 1; }

# Make sure that we're running on OS X.
[ "$(uname)" = 'Darwin' ] || die "FAILED TEST PREREQUISITE: Can only run on OSX."

# Make sure that either Alfred 2 or Alfred 3 are installed.
# !! For now, even if BOTH are installed, we ONLY test with the HIGHER version.
osascript -e 'tell application "Alfred 3" to id' &>/dev/null || osascript -e 'tell application "Alfred 2" to id' &>/dev/null || die "FAILED TEST PREREQUISITE: Alfred 3 or Alfred 2 must be installed."

exit 0
